name: aplicativo
description: "Aplicativo de GestÃ£o de Atendimentos"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: 8.1.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  assets:  
    - assets/images/logo.png